version: "3.4"

services:
  frontend:
    image: node:lts
    volumes:
      - ./FrontEnd:/frontend
      - /frontend/node_modules
    env_file:
      .env
    container_name: "frontend"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=frontend"
      - "traefik.port=3000"
      - "traefik.frontend.rule=PathPrefix: /"
      - "traefik.website.frontend.whiteList.sourceRange=${TRAEFIK_IPFILTER:-172.16.0.0/12}"
    command: /bin/sh -c "cd frontend; yarn; yarn install; yarn start"
  
  api:
    image: api
    build:
      context: ./WebAPI
      target: publish
      dockerfile: ./API.Dockerfile
  
  pythonrpcserver:
    image: pythonrpcserver
    build:
      context: ./WebAPI
        dockerfile: ./pythonrpcserver.Dockerfile
      
  
  taskengine:
    image: taskengine
    build:
      context: ./WebAPI
      target: publish
      dockerfile: ./TaskEngine.Dockerfile
  
  rabbitmq:
    ports:
      - "5672:5672"
  
  pythonrpcserver:
    ports:
      - "50051:50051"